### ISSUE TITLE
dimensions package dependency

### ISSUE THREAD

**Issue by montasaurus** [sreejithr/react-native-slide-button#5] opened 2016-09-28 21:58 UTC
Hi, I got some npm errors when I went to use this package.

It seems like the `dimensions` npm package is being referenced, but isn't declared as a dependency in `package.json`. The `dimensions` library has a further dependency on `fs`, which [doesn't appear to be available from a react native environment](http://stackoverflow.com/questions/39046429/react-native-unable-to-resolve-module-fs).

It looks like it would be safe to just remove this dependency completely, along with the `SCREEN_WIDTH` and `SCREEN_HEIGHT` properties.

**Comment by sreejith-driveu** [comment] 2016-09-29 10:14
@howitzer-industries You're right, since we're not using `SCREEN_WIDTH` and `SCREEN_HEIGHT` anywhere, we can remove these lines. But `Dimensions` is not an external dependency, you see. It is part of react-native ([link](https://facebook.github.io/react-native/docs/dimensions.html)).

**Comment by sreejithr** [comment] 2016-09-29 12:51
@howitzer-industries You're right, since we're not using SCREEN_WIDTH and SCREEN_HEIGHT anywhere, we can remove these lines. But Dimensions is not an external dependency, you see. It is part of react-native (link).

**Comment by sreejithr** [comment] 2016-09-29 12:55
@howitzer-industries I was able to reproduce the error you were mentioning. I've made a pull request fixing the issue.

**Edit**: Merged.

**Comment by sreejithr** [comment] 2016-09-29 14:54
@howitzer-industries This fix and couple of other fixes and features have been released as [v1.3.0](https://github.com/sreejithr/react-native-slide-button/releases/tag/v1.3.0).

**Closed as completed** 2016-12-16 11:50 UTC
